local H = require("tests.test_helper")
local Bracket = require("AstralArena.Core.Bracket")

local function seededBracket()
    local state = Bracket.new({ id = "test" })
    for seed = 1, 8 do
        Bracket.register(state, { id = "p" .. seed, displayName = "Player " .. seed })
    end
    Bracket.seed(state)
    return state
end

H.test("standard seeding keeps top seeds apart", function()
    local state = seededBracket()
    H.equal(state.entrants.p1.currentLevel, 5)
    H.equal(state.matches.QF1.level, 5)
    H.equal(state.matches.QF1.leftEntrantId, "p1")
    H.equal(state.matches.QF1.rightEntrantId, "p8")
    H.equal(state.matches.QF2.leftEntrantId, "p4")
    H.equal(state.matches.QF3.leftEntrantId, "p2")
    H.equal(state.matches.QF4.leftEntrantId, "p3")
    H.equal(#Bracket.readyMatches(state), 4)
end)

H.test("quarterfinal winners advance at level eight", function()
    local state = seededBracket()
    Bracket.recordWinner(state, "QF1", "p1")
    H.equal(state.entrants.p1.currentLevel, 8)
    H.truthy(state.entrants.p8.eliminated)
    H.equal(state.matches.SF1.leftEntrantId, "p1")
    H.equal(state.matches.SF1.status, "waiting")

    Bracket.recordWinner(state, "QF2", "p4")
    H.equal(state.matches.SF1.rightEntrantId, "p4")
    H.equal(state.matches.SF1.status, "ready")
    H.equal(state.matches.SF1.level, 8)
end)

H.test("three wins produce a level twelve champion", function()
    local state = seededBracket()
    Bracket.recordWinner(state, "QF1", "p1")
    Bracket.recordWinner(state, "QF2", "p4")
    Bracket.recordWinner(state, "QF3", "p2")
    Bracket.recordWinner(state, "QF4", "p3")
    Bracket.recordWinner(state, "SF1", "p1")
    H.equal(state.entrants.p1.currentLevel, 10)
    Bracket.recordWinner(state, "SF2", "p2")
    H.equal(state.matches.F1.level, 10)
    Bracket.recordWinner(state, "F1", "p1")

    H.equal(state.status, "completed")
    H.equal(state.championEntrantId, "p1")
    H.equal(state.entrants.p1.currentLevel, 12)
    H.equal(#state.history, 8)
end)

H.test("an unassigned winner is rejected", function()
    local state = seededBracket()
    H.raises(function()
        Bracket.recordWinner(state, "QF1", "p2")
    end, "winner is not assigned")
end)

H.test("registration rejects duplicate entrants", function()
    local state = Bracket.new()
    Bracket.register(state, { id = "same", displayName = "First" })
    H.raises(function()
        Bracket.register(state, { id = "same", displayName = "Second" })
    end, "already registered")
end)
